stages:
  - build
  - test
  - deploy

build:
  image: ruby:3.1
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
  script:
    - if [ -f package.json ]; then
        npm install && npm run build;
      else
        echo "No package.json, skipping npm install/build";
      fi

deploy:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
