name: Sync to GitLab

on:
  push:
    branches: [ GitLabForce ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to GitLab
        uses: kujov/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username:   ${{ secrets.GITLAB_USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
          force_push: true
